### ISSUE TITLE
Boradcast bug with undo/redo 

### ISSUE THREAD

**Issue by andrea78** [lbovet/wb0#2]
Hi Laurent,
Thanks for your great fork. I've learned a lot from you.
There is a bug. When we're clicking undo and redo, extra lines appear when we're using a pencil. Screens below.
BEFORE UNDO REDO
![Scr](https://user-images.githubusercontent.com/461774/133862239-466b1d16-7c95-41fd-9848-c3e0257a906a.png)
AFTER UNDO REDO
![S](https://user-images.githubusercontent.com/461774/133862255-d6c95e5b-6b2b-4ed1-91af-616f52502e92.png)
How to reproduce it?
1. Create the first whiteboard.
2. Open the same whiteboard in other browser window or in another browser.
3. Write anything with a pencil on the first whitebord for example GITHUB.COM.
3. Click at least once the undo button on the second whiteboard and go to the first one.
4. You should see these extra lines now.

**Comment by lbovet** [comment]
I cannot reproduce that. Can you give more info about your setup? Are you on the master branch?

**Comment by andrea78** [comment]
I've found a reason. Previously I've tested your commits on Jun 6, 2021. Now I'm testing your commits on Jun 16, 2021. After resetting my VPS, undo/redo now works fine.
